media: 
  input: src/assets
  output: ../../assets
content:
  - name: posts
    label: Posts
    path: src/content/blog
    type: collection
    fields:
      - name: 'title'
        type: string
      - name: 'description'
        type: string
      - name: 'pubDate'
        type: date
      - name: 'heroImage'
        type: image
      - name: 'heroLink'
        type: string
      - name: 'heroLinkText'
        type: string
      - name: 'category'
        type: string
      - name: 'published'
        type: boolean
      - name: 'body'
        type: rich-text
      - name: 'newcodefield'
        type: code